name: CavernCarver
main: ca.mcpnet.CavernCarver.CavernCarver
version: 0.0.1
description: Carve caverns automatically from the player position
author: globnobulous
commands:
   cc_cavern:
      description: carve out a cavern from where the player is standing
      permission: caverncarver.cc_cavern
      usage: /<command> size [player]
   cc_maxradius:
      description: set the maximum allowable radius for cavern carving
      permission: caverncarver.cc_maxradius
      usage: /<command> radius
permissions:
   caverncarver.cc_cavern:
      description: allows player to execute the cc_cavern command
      default: op
   caverncarver.cc_maxradius:
      description: allows player to execute the cc_maxradius command
      default: op